### PR TITLE
ORFs AA size should not include the terminal codon translation *

### PR DESCRIPTION
**Pull request by XingGao-PKI**
When a DNA/RNA translated to AA sequence in ORFs, a terminal codon translation * is always included, this is not a valid AA, we should reduce one AA from the AA size.

E.g: this sequence
atgactgaatacaagcctactgtcaggttggctacaagagacgacgttcctagagccgtgagaactctggctgcagccttcgccgactaccccgccacgagacacaccgttgacccagatcggcatattgagagagtgactgaactgcaggagctgtttcttacaagagttggcctcgacataggcaaggtgtgggtggcggacgacggcgccgccgtggccgtctggaccactcccgaatcagttgaggctggcgccgtattcgctgagatcggcccgagaatggctgagctcagcgggagtaggctcgcggcacagcagcaaatggagggactgctggcaccacacaggcccaaagaacccgcctggttcctggcaaccgtcggtgtatctcccgatcatcaggggaaaggtctgggctctgccgtagtgctccctggcgtggaggcagctgagagagcaggagtacctgccttcttggagacctccgctccaaggaatcttcccttctatgaacggttgggcttcaccgtgacagccgacgtggaagtccccgaaggcccccgcacttggtgcatgacgaggaagcctggagcgtga
is translate to AA sequence MTEYKPTVRLATRDDVPRAVRTLAAAFADYPATRHTVDPDRHIERVTELQELFLTRVGLDIGKVWVADDGAAVAVWTTPESVEAGAVFAEIGPRMAELSGSRLAAQQQMEGLLAPHRPKEPAWFLATVGVSPDHQGKGLGSAVVLPGVEAAERAGVPAFLETSAPRNLPFYERLGFTVTADVEVPEGPRTWCMTRKPGA*
This AA string size is 200, but the actual valid AA size should be 199.

### CODE REVIEW

**Comment by tnrich** [comment]
@XingGao-PKI thank you for this excellent PR. Could you please set up a simple cypress test for it? 

Thank you!

**Comment by XingGao-PKI** [comment]
Close PR and Reopen to trigger the Blocked Cypress tests

**Review by tnrich — APPROVED** [review]
Nice work @XingGao-PKI ! Thank you!

**Comment by tnrich** [comment]
Published a new version 16.3.35 for you @XingGao-PKI

**Pull request merged**
