### PR TITLE
Truncate long external labels row view

### PR DESCRIPTION
**Pull request by ericsturman**
@tnrich we noticed that external labels that are very long do not get truncated in the rare case that they run longer than the width of the RowView.  I have applied a fix.  Let me know if you want a test case for this.  Also, I was wanting to add the same tool tip to the external label that a user would see when mousing over the feature but it wasn't clear to me how to get started.  Any help would be appreciated.

### CODE REVIEW

**Comment by tnrich** [comment]
Hey @ericsturman thanks for the fix! 

Is this what you're thinking of when you say you want a tooltip on the label?

image

**Comment by ericsturman** [comment]
yes

**Review by tnrich — APPROVED** [review]

**Comment by tnrich** [comment]
@ericsturman I think I've fixed the title text stuff. I've merged in your changes and published a new version 16.1.26. 

Do you think you could write a little test for your new label functionality and checking that the titles are as you'd expect? 

Cheers!
Thomas

**Comment by ericsturman** [comment]
Thank you!  I'll submit a test Monday... Have a great weekend!

**Pull request merged**
