### PR TITLE
Update dependency react-dropzone to latest version

### PR DESCRIPTION
**Pull request by smeng9**
Hi I would like to pin the react-dropzone to a higher version

so I can use hooks like `useDropzone` in some other parts of my project.

Thanks

### CODE REVIEW

**Comment by tnrich** [comment]
Hey @smeng9 do you know if the latest version of react drop zone is fully compatible with the current version in use?

**Comment by smeng9** [comment]
I will try to run some regression test

**Comment by smeng9** [comment]
Hey @tnrich, I have finished bumping the versions. Can you help to review the code? Thanks!

Also can you enable running the GitHub workflow for me? For now I can only run e2e tests locally.

**Comment by smeng9** [comment]
I have tried to run the same tests on master branch, seems there are already 12 failures

**Comment by smeng9** [comment]
I have finished fixing all the tests related to Dropzone.

**Comment by tnrich** [comment]
Hey @smeng9 sorry for the delayed responses to this, I'm traveling right now and taking a vacation. I'll try to take a look at this now

**Comment by tnrich** [comment]
Hey @smeng9, react-dropzone is also in use by teselagen-react-components (https://github.com/TeselaGen/teselagen-react-components), a dependency of this repo. react-dropzone will also need to be updated in that repo as well in order for me to be able to take the changes from here.

**Comment by tnrich** [comment]
@smeng9 also do you know why you're getting the failing tests here: 
image

The latest runs off master seem to be doing just fine: 
image

**Comment by smeng9** [comment]
Hi @tnrich 

I don't know why the failing tests come up in the cypress. They seems are not related to the react-dropzone.

However I do run into some issues with the test-e2e setup. The papaparse and the downloadjs are missing from the dependencies. Then I have to manually add them. After that I still cannot pass all the tests even on master branch.

**Comment by smeng9** [comment]
I also tried to run the examples in teselagen-react-components by `yarn start` However when I opened the page at localhost:3333 I only see a line `succeeded!`

**Comment by tnrich** [comment]
@smeng9 hmm I'll need to help you debug this some more but will be on vacation for a week longer. After that I'm happy to schedule some time to pair in person to get things working for you if you'd like.

**Comment by smeng9** [comment]
No problem, enjoy your vacation.

**Comment by smeng9** [comment]
Hi @tnrich, we can schedule to pair to solve the issue after thanksgiving break.

**Comment by tnrich** [comment]
Sure, shoot me a message after Thanksgiving break

**Comment by tnrich** [comment]
@smeng9 lemme know when you'd like to pair to resolve your issues :)

**Comment by smeng9** [comment]
can we do this Friday 1pm PT? Thanks for the help.

**Comment by tnrich** [comment]
Sure Friday at 1pm California time works for me.

**Comment by smeng9** [comment]
I will share you the zoom link https://illinois.zoom.us/j/85100282947?pwd=NWljWTdQZ3hMMzhkUS81RVQ3UGgwdz09

**Review by tnrich — COMMENTED** [review]
Now that TRC is updated we should be able to take these changes.

**Comment by tnrich** [comment]
Ok, this has been released in v17.0.1

Cheers!

**Pull request merged**
