### PR TITLE
Add Editor prop to disable dragging tab

### PR DESCRIPTION
**Pull request by onesjtuer**
adding new prop `allowPanelTabDraggable` to `Editor` to make the dragging tab configurable

### CODE REVIEW

**Comment by tnrich** [comment]
@onesjtuer looks good to me. Could you please add this as an option to the demo page as well. Thank you!

**Comment by onesjtuer** [comment]
added

**Review by tnrich — APPROVED** [review]

**Comment by tnrich** [comment]
Awesome thanks @onesjtuer publishing a new version for you now!

**Comment by tnrich** [comment]
open-vector-editor@16.3.7

**Pull request merged**
