### PR TITLE
 update react and redux

### PR DESCRIPTION
**Pull request by tnrich**

### CODE REVIEW

**Comment by XingGao-PKI** [comment]
@tnrich, Seems you have publish the wrong branch on npm. Could you check that ?

image

**Comment by tnrich** [comment]
@XingGao-PKI I think that branch should be published as a beta. Is it not?

**Comment by XingGao-PKI** [comment]
@tnrich, Nope, I used the formal publish `17.0.12`

**Comment by tnrich** [comment]
@XingGao-PKI thanks I've merged this PR and am publishing the changes as open-vector-editor@17.1.4

**Comment by XingGao-PKI** [comment]
@tnrich, Cool, Thanks.

**Pull request merged**
