### PR TITLE
Es labels

### PR DESCRIPTION
**Pull request by ericsturman**
@tnrich I have wrapped up the code changes and added an e2e test...

### CODE REVIEW

**Comment by ericsturman** [comment]
One thing I did notice is that the cutsite labels look a little weird below the sequence text in the `Sequence Map`.  If the sequence text is present in the `RowView` we might want to have them positioned above the cutsite box.  What do you think?

**Comment by tnrich** [comment]
@ericsturman good catch on the cutsite labels, I didn't realize I had put them too far down in the stack

**Comment by tnrich** [comment]
@ericsturman I'm going to merge this in, fix the issues you mentioned and make a few additional changes to allow this to be user configurable and persisted to localstorage. I'll let you know when I cut a release.

**Comment by tnrich** [comment]
@ericsturman whoops didn't realize you added the persisted options already

**Comment by ericsturman** [comment]
@tnrich This looks great; we do great work!  I did notice that in the `Sequence Map` there are some restriction enzymes not getting their label (ex: `NruI` at 619 in the demo page).  It looks like it needs to be an exception from the `onlyShowLabelsThatDoNotFit` logic.

**Comment by tnrich** [comment]
@ericsturman good catch! That makes sense. We don't want to filter out any cutsite labels at all there. I'll fix that

**Comment by tnrich** [comment]
@ericsturman fixed in v10.1.53

**Pull request merged**
