### PR TITLE
fix warning on css import order

### PR DESCRIPTION
**Pull request by smeng9**
Fix following warning during vite build

Screenshot from 2022-11-18 00-55-01

### CODE REVIEW

**Review by tnrich — APPROVED** [review]
Awesome thanks @smeng9 !

**Comment by tnrich** [comment]
@smeng9 publishing this in v18.1.48 now! Lemme know if that does it for ya!

**Comment by tnrich** [comment]
Also, could you link to where you're bundling OVE using vite? (if it's a public repo that is)! 

Thanks,
Thomas

**Comment by smeng9** [comment]
I can publish a tutorial to use vite.

It provides so much speed up

**Comment by tnrich** [comment]
@smeng9 please let me know when you publish that tutorial and include a link to it. Thanks!

**Comment by smeng9** [comment]
Hi @tnrich https://stackblitz.com/edit/vitejs-vite-tglega?file=package.json&terminal=dev
Its based off https://github.com/tnrich/ove-react-demo-repo
Vite provides so much speed up than CRA.

**Comment by tnrich** [comment]
Thanks for posting this @smeng9 ! I'm definitely interested in trying out using vite as the default bundler for developing OVE

**Pull request merged**
